### ISSUE TITLE
ovnkube fails to restart after node deletion

### ISSUE THREAD

**Issue by freedge** [ovn-org/ovn-kubernetes#3168] opened 2022-09-20 09:01 UTC
When a pod is stuck in Terminating state on a deleted node, ovnkube fails to restart.

using ovn-kubernetes on kind:
```
kubectl run --overrides="{ \"metadata\": { \"finalizers\": [\"foo/bar\"] }, \"spec\": {\"nodeSelector\": { \"kubernetes.io/hostname\": \"ovn-worker2\" } } }"   \
   --restart=Never --image alpine  myclient -- sleep 1
kubectl delete node ovn-worker2
kubectl delete pod -n ovn-kubernetes -l name=ovnkube-master
kubectl logs -n ovn-kubernetes -l name=ovnkube-master -c ovnkube-master -f
```
In this state, pod/myclient is in Terminating state on node/ovn-worker2, which does not exist anymore.

Notably we read log:
```
Failed to wait for node ovn-worker2 to be added to cache. IP allocation may fail!
```

we also notice this in the logs (an extra!)
```
2022-09-20T08:43:57.336Z|00004|fatal_signal(ovn_pinctrl0)|WARN|terminating with signal 11 (Segmentation fault) 
```
When this happens the cluster is unusable as no pod is added in the north db.

We can recover by removing the finalizer.

EDIT: I am working on a more reliable reproducer as this one seems to only reproduce the issue intermittently

**Comment by flavio-fernandes** [comment] 2022-09-23 22:36
@freedge this has been fixed via https://github.com/flavio-fernandes/ovn-kubernetes/commit/f1be8d298bfe7b087af009a4093a863ebb7804fb

**Comment by freedge** [comment] 2022-09-24 06:05
it persists after pr checkout 3177. ovnkube-master is in crashloopbackoff.

fyi this is the reproducer I use (it might be too much but it reproduces everytime in kind)

```
cat | kubectl apply -f - << EOF
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: anetpol
  spec:
    egress:
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            foo: bar
    ingress:
    - from:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            foo: bar
    podSelector:
      matchLabels:
        foo: bar
    policyTypes:
    - Ingress
    - Egress

kind: List
metadata:
  resourceVersion: ""
EOF

L=foo=bar
kubectl run --labels $L \
   --overrides="{ \"metadata\": { \"finalizers\": [\"foo/bar\"] }, \"spec\": {\"nodeSelector\": { \"kubernetes.io/hostname\": \"ovn-worker2\" } } }"   \
   --restart=Never --image alpine  myclient -- sleep 1
sleep 10
kubectl run --labels $L \
   --overrides="{ \"metadata\": { \"finalizers\": [\"foo/bar\"] }, \"spec\": {\"nodeSelector\": { \"kubernetes.io/hostname\": \"ovn-worker2\" } } }"   \
   --restart=Never --image alpine  myclient2 -- sleep 1
kubectl run --labels $L \
   --overrides="{ \"metadata\": { \"finalizers\": [\"foo/bar\"] }, \"spec\": {\"nodeSelector\": { \"kubernetes.io/hostname\": \"ovn-worker2\" } } }"   \
   --restart=Never --image alpine  myclient3 -- sleep 1000
sleep 10
kubectl delete --wait=false pod myclient
sleep 10
kubectl delete node ovn-worker2
sleep 10
kubectl run --labels foo=bar --restart=Never --image alpine  myclient4 -- sleep 1
sleep 10
kubectl delete pod -n ovn-kubernetes -l name=ovnkube-master
sleep 120
kubectl run --labels $L --restart=Never --image alpine  myclient5 -- sleep 1
kubectl run --labels $L \
   --overrides="{ \"metadata\": { \"finalizers\": [\"foo/bar\"] }, \"spec\": {\"nodeSelector\": { \"kubernetes.io/hostname\": \"ovn-worker\" } } }"   \
   --restart=Never --image alpine  myclient6 -- sleep 1000

```

new pods are stuck in containercreating:
```
$ kubectl  get pods -o wide
NAME        READY   STATUS              RESTARTS   AGE   IP           NODE          NOMINATED NODE   READINESS GATES
myclient    0/1     Terminating         0          30m   10.244.2.3   ovn-worker2   <none>           <none>
myclient2   0/1     Terminating         0          29m   10.244.2.5   ovn-worker2   <none>           <none>
myclient3   0/1     Terminating         0          29m   10.244.2.4   ovn-worker2   <none>           <none>
myclient4   0/1     Completed           0          29m   10.244.1.6   ovn-worker    <none>           <none>
myclient5   0/1     ContainerCreating   0          27m   <none>       ovn-worker    <none>           <none>
myclient6   0/1     ContainerCreating   0          27m   <none>       ovn-worker    <none>           <none>
```

```
$ kubectl  get pods -n ovn-kubernetes -l name=ovnkube-master
NAME                              READY   STATUS             RESTARTS        AGE
ovnkube-master-5b5ddf8879-ccdhf   1/2     CrashLoopBackOff   7 (4m57s ago)   35m
```
last logs before crash


```
...failed to wait for node ovn-worker2 to be added to cache. IP allocation may fail!
E0924 05:43:52.063890      39 master.go:110] watchResource for resource *v1.Pod. Failed addHandlerFunc: timed out waiting for the condition
I0924 05:43:52.064243      39 metrics.go:445] Stopping metrics server 10.89.0.3:9409
I0924 05:43:52.064345      39 reflector.go:225] Stopping reflector *v1.Service (0s) from k8s.io/client-go/informers/factory.go:134
I0924 05:43:52.064453      39 obj_retry.go:1203] Stop channel got triggered: will stop retrying failed objects of type *v1.Node
I0924 05:43:52.064539      39 reflector.go:225] Stopping reflector *v1.Service (0s) from k8s.io/client-go/informers/factory.go:134
I0924 05:43:52.064489      39 reflector.go:225] Stopping reflector *v1.Namespace (0s) from k8s.io/client-go/informers/factory.go:134
I0924 05:43:52.064612      39 obj_retry.go:1203] Stop channel got triggered: will stop retrying failed objects of type *v1.Namespace
I0924 05:43:52.064247      39 reflector.go:225] Stopping reflector *v1.Node (0s) from k8s.io/client-go/informers/factory.go:134
I0924 05:43:52.064748      39 reflector.go:225] Stopping reflector *v1.EndpointSlice (0s) from k8s.io/client-go/informers/factory.go:134
I0924 05:43:52.064824      39 reflector.go:225] Stopping reflector *v1.EgressFirewall (0s) from pkg/crd/egressfirewall/v1/apis/informers/externalversions/factory.go:117
I0924 05:43:52.064887      39 services_controller.go:179] Shutting down controller ovn-lb-controller
I0924 05:43:52.065055      39 reflector.go:225] Stopping reflector *v1.NetworkPolicy (0s) from k8s.io/client-go/informers/factory.go:134
I0924 05:43:52.064924      39 reflector.go:225] Stopping reflector *v1.EgressIP (0s) from pkg/crd/egressip/v1/apis/informers/externalversions/factory.go:117
I0924 05:43:52.065009      39 reflector.go:225] Stopping reflector *v1.EgressQoS (0s) from pkg/crd/egressqos/v1/apis/informers/externalversions/factory.go:117
I0924 05:43:52.065138      39 reflector.go:225] Stopping reflector *v1.Node (0s) from k8s.io/client-go/informers/factory.go:134
I0924 05:43:52.065305      39 reflector.go:225] Stopping reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:134
I0924 05:43:52.065325      39 handler.go:140] Sending *v1.Node event handler 2 for removal
I0924 05:43:52.065457      39 handler.go:148] Removed *v1.Node event handler 2
I0924 05:43:52.065502      39 handler.go:140] Sending *v1.Namespace event handler 1 for removal
I0924 05:43:52.065716      39 handler.go:148] Removed *v1.Namespace event handler 1
I0924 05:43:52.101657      39 master.go:120] No longer leader; exiting
I0924 05:43:52.102438      39 master.go:140] Stopped leader election
=============== pid 39 terminated ========== 
```

btw I set dbg logs on ovn-controller and failed to reproduce the core yet
```
$  sudo coredumpctl list ovn-controller
Journal file /var/log/journal/7cc190ccb4304882b182dd6a3b7eeed7/system@0005e6304bba8757-8230e9a4cb91716a.journal~ is truncated, ignoring file.
TIME                           PID UID GID SIG     COREFILE EXE                       SIZE
Tue 2022-09-20 10:31:12 CEST  8662   0   0 SIGSEGV missing  /usr/bin/ovn-controller    n/a
Tue 2022-09-20 10:31:13 CEST  8738   0   0 SIGSEGV missing  /usr/bin/ovn-controller    n/a
Tue 2022-09-20 10:43:58 CEST 21708   0   0 SIGSEGV missing  /usr/bin/ovn-controller    n/a
Tue 2022-09-20 10:43:58 CEST 21716   0   0 SIGSEGV missing  /usr/bin/ovn-controller    n/a
Wed 2022-09-21 11:21:15 CEST  8222   0   0 SIGSEGV missing  /usr/bin/ovn-controller    n/a
Wed 2022-09-21 14:30:51 CEST  8124   0   0 SIGSEGV missing  /usr/bin/ovn-controller    n/a
Wed 2022-09-21 15:15:51 CEST 48667   0   0 SIGSEGV present  /usr/bin/ovn-controller 762.3K
```
I opened https://bugzilla.redhat.com/show_bug.cgi?id=2128644 for that one.

**Comment by flavio-fernandes** [comment] 2022-09-24 09:51
@freedge:
Thank you for giving more info on how you are reproducing this issue. It looks to me that there is a part related to OVS that we may need to track separately so we are not mixing ovnk8 with it.

- Can you show more details on how you are deploying your kind cluster?
Are you using `-ha` ?
- What version of kind are you using (kind --version) ?
- What image is used for the nodes (docker ps) ?
- I think that NetworkPolicy has nothing to do with this issue, so you may simplify your steps.
- When you `kubectl delete node ovn-worker2` you should also `docker stop ovn-worker2' because that is going to make ovs very confused! Can you please try reproducing the issue that way?

Thanks,
-- flaviof

**Comment by flavio-fernandes** [comment] 2022-09-24 10:03
This is where I'm currently seeing the ovnkube-master process failing:
```
I0924 09:56:27.114056      40 leaderelection.go:278] successfully renewed lease ovn-kubernetes/ovn-kubernetes-master
I0924 09:56:27.217966      40 obj_retry.go:1173] Going to retry *v1.Namespace resource setup for 0 number of resources: []
I0924 09:56:27.218021      40 obj_retry.go:1182] Waiting for all the *v1.Namespace retry setup to complete in iterateRetryResources
I0924 09:56:27.218055      40 obj_retry.go:1184] Function iterateRetryResources ended (in 106.255µs)
I0924 09:56:27.274849      40 obj_retry.go:1173] Going to retry *v1.Node resource setup for 0 number of resources: []
I0924 09:56:27.274898      40 obj_retry.go:1182] Waiting for all the *v1.Node retry setup to complete in iterateRetryResources
I0924 09:56:27.274907      40 obj_retry.go:1184] Function iterateRetryResources ended (in 71.293µs)
E0924 09:56:28.318102      40 factory.go:489] Failed (will retry) in processExisting [&Pod{ObjectMeta:{kube-controller-manager-ovn-control-plane  kube-system  05694032-43e0-4f8d-8eda-17015220fe3b 414 0 2022-09-24 09:29:25 +0000 UTC <nil> <nil> map[\
component:kube-controller-manager tier:control-plane] map[kubernetes.io/config.hash:6da620fdd56b0d0f4ab0c498d0352175 kubernetes.io/config.mirror:6da620fdd56b0d0f4ab0c498d0352175 kubernetes.io/config.seen:2022-09-24T09:29:25.242246651Z kubernetes.io\
/config.source:file seccomp.security.alpha.kubernetes.io/pod:runtime/default]
...
PodCondition{PodCondition{Type:Initialized,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,Las\
tTransitionTime:2022-09-24 09:34:06 +0000 UTC,Reason:,Message:,},PodCondition{Type:Ready,Status:False,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2022-09-24 09:35:48 +0000 UTC,Reason:ContainersNotReady,Message:containers with unr\
eady status: [myclient3],},PodCondition{Type:ContainersReady,Status:False,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2022-09-24 09:35:48 +0000 UTC,Reason:ContainersNotReady,Message:containers with unready status: [myclient3],},P\
odCondition{Type:PodScheduled,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2022-09-24 09:34:06 +0000 UTC,Reason:,Message:,},},Message:,Reason:,HostIP:172.18.0.3,PodIP:10.244.0.8,StartTime:2022-09-24 09:34:06 +0000 UTC,\
ContainerStatuses:[]ContainerStatus{ContainerStatus{Name:myclient3,State:ContainerState{Waiting:nil,Running:nil,Terminated:&ContainerStateTerminated{ExitCode:137,Signal:0,Reason:Error,Message:,StartedAt:2022-09-24 09:34:09 +0000 UTC,FinishedAt:2022\
-09-24 09:35:48 +0000 UTC,ContainerID:containerd://51cac622e41458bcf64bc22673c9d3bdd5f881c6af99590d20bbebb5e1a287ce,},},LastTerminationState:ContainerState{Waiting:nil,Running:nil,Terminated:nil,},Ready:false,RestartCount:0,Image:docker.io/library/\
alpine:latest,ImageID:docker.io/library/alpine@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad,ContainerID:containerd://51cac622e41458bcf64bc22673c9d3bdd5f881c6af99590d20bbebb5e1a287ce,Started:*false,},},QOSClass:BestEffort,\
InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{PodIP{IP:10.244.0.8,},},EphemeralContainerStatuses:[]ContainerStatus{},},}]: failed to wait for node ovn-worker2 to be added to cache. IP allocation may fail!
E0924 09:56:28.341931      40 master.go:110] watchResource for resource *v1.Pod. Failed addHandlerFunc: timed out waiting for the condition
I0924 09:56:28.342974      40 reflector.go:225] Stopping reflector *v1.Service (0s) from k8s.io/client-go/informers/factory.go:134
I0924 09:56:28.343773      40 handler.go:140] Sending *v1.Namespace event handler 1 for removal
I0924 09:56:28.343861      40 handler.go:140] Sending *v1.Node event handler 2 for removal
I0924 09:56:28.343906      40 handler.go:148] Removed *v1.Node event handler 2
I0924 09:56:28.343534      40 obj_retry.go:1203] Stop channel got triggered: will stop retrying failed objects of type *v1.Node
I0924 09:56:28.343561      40 obj_retry.go:1203] Stop channel got triggered: will stop retrying failed objects of type *v1.Namespace
I0924 09:56:28.343604      40 services_controller.go:179] Shutting down controller ovn-lb-controller
I0924 09:56:28.343660      40 metrics.go:445] Stopping metrics server 172.18.0.2:9409
I0924 09:56:28.347700      40 reflector.go:225] Stopping reflector *v1.EgressFirewall (0s) from pkg/crd/egressfirewall/v1/apis/informers/externalversions/factory.go:117
I0924 09:56:28.347856      40 reflector.go:225] Stopping reflector *v1.EgressIP (0s) from pkg/crd/egressip/v1/apis/informers/externalversions/factory.go:117
I0924 09:56:28.347973      40 reflector.go:225] Stopping reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:134
I0924 09:56:28.343938      40 handler.go:148] Removed *v1.Namespace event handler 1
I0924 09:56:28.346878      40 reflector.go:225] Stopping reflector *v1.Node (0s) from k8s.io/client-go/informers/factory.go:134
I0924 09:56:28.346966      40 reflector.go:225] Stopping reflector *v1.EndpointSlice (0s) from k8s.io/client-go/informers/factory.go:134
I0924 09:56:28.347019      40 reflector.go:225] Stopping reflector *v1.NetworkPolicy (0s) from k8s.io/client-go/informers/factory.go:134
I0924 09:56:28.347355      40 reflector.go:225] Stopping reflector *v1.Service (0s) from k8s.io/client-go/informers/factory.go:134
I0924 09:56:28.347620      40 reflector.go:225] Stopping reflector *v1.Node (0s) from k8s.io/client-go/informers/factory.go:134
I0924 09:56:28.348074      40 reflector.go:225] Stopping reflector *v1.EgressQoS (0s) from pkg/crd/egressqos/v1/apis/informers/externalversions/factory.go:117
I0924 09:56:28.349913      40 reflector.go:225] Stopping reflector *v1.Namespace (0s) from k8s.io/client-go/informers/factory.go:134
I0924 09:56:28.413180      40 master.go:120] No longer leader; exiting
I0924 09:56:28.414279      40 master.go:140] Stopped leader election
=============== pid 40 terminated ==========
```

**Comment by freedge** [comment] 2022-09-24 12:15
this is a fedora rawhide VM, kind version 0.14.0, I just run "sudo ./kind.sh -ep podman" which runs fedora:36 based images.

>  I think that NetworkPolicy has nothing to do with this issue, so you may simplify your steps.

so the initial steps I give in the ticket should work but not super reliably, there might be some race condition somewhere... 

> that is going to make ovs very confused!

Actually I tried it once more and this time got a SIGSEGV of ovs at exit time it seems
```
#0  0x00007fe73cf944dd in rule_destroy_cb () from /lib64/libofproto-2.17.so.0
#1  0x00007fe73cdb5f8e in ovsrcu_call_postponed () from /lib64/libopenvswitch-2.17.so.0
#2  0x00007fe73cdb6362 in ovsrcu_exit () from /lib64/libopenvswitch-2.17.so.0
#3  0x000055f864d4aca7 in main ()
```

**Closed** 2022-09-26 13:47 UTC
