### ISSUE TITLE
e2e failure: Granular Checks: Services Secondary IP Family [LinuxOnly] should function for service endpoints using hostNetwork

### ISSUE THREAD

**Issue by npinaeva** [ovn-org/ovn-kubernetes#3190] opened 2022-09-28 13:11 UTC
e2e (shard-conformance, HA, local, dualstack, snatGW, 1br) fails after 5 retries

https://github.com/ovn-org/ovn-kubernetes/actions/runs/3143018367/jobs/5107602686

[e2e-dual-conversion (local)](https://github.com/ovn-org/ovn-kubernetes/actions/runs/3128202869/jobs/5076118815#logs)

**Comment by npinaeva** [comment] 2022-09-30 10:23
https://github.com/ovn-org/ovn-kubernetes/actions/runs/3114015023/jobs/5049663936 Sep 23 16:32:31.115
https://github.com/ovn-org/ovn-kubernetes/actions/runs/3099377311/jobs/5020124022 Sep 21 20:27:38.890
https://github.com/ovn-org/ovn-kubernetes/actions/runs/3001613118/jobs/4818181945 Sep  6 16:33:19.274
https://github.com/ovn-org/ovn-kubernetes/actions/runs/2892390991/jobs/4625914298 Aug 22 18:28:57.000
https://github.com/ovn-org/ovn-kubernetes/actions/runs/2746242673/jobs/4307559676 Jul 27 11:54:11.629
https://github.com/ovn-org/ovn-kubernetes/actions/runs/2630025558/jobs/4079032757 Jul  7 14:32:59.205
it fails for more than 3 months

**Comment by trozet** [comment] 2022-09-30 21:01
note also seeing this downstream: 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1275/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack/1575552800513855488

https://github.com/openshift/ovn-kubernetes/pull/1275

Looking at a failure from upstream:
https://pipelines.actions.githubusercontent.com/serviceHosts/420fda10-250e-4b5e-ad0c-d969a2d4a803/_apis/pipelines/1/runs/84701/signedlogcontent/50?urlExpires=2022-09-30T15%3A25%3A57.6726530Z&urlSigningMethod=HMACV1&urlSignature=e7TztCZLv%2Fo2nXsPtecS%2BznNpJXq0oSH79B322Itw2o%3D

This test has a bunch of different scenarios, but the one that is consistently failing is pod -> another node's nodeport. The test case creates an ovn-networked pod (test container) on a node, and then 3 host networked endpoints. It expects that:

1. Attempting to curl from inside the test container to the cluster IP of an ipv6 service multiple times should eventually hit every endpoint - this passes.
2. Attempting to curl from inside the test container to one of the node ports multiple times should eventually hit every endpoint - this flakes in a specific way.

What I see is that for scenario 2, 1/3 endpoints will not be hit, and it is always the one that is locally hosted at the same node where the nodeport is being accessed. In other words consider we have nodes A, B, C each with a host networked endpoint and the test container lives on node A. Test container tries to access the nodeport on node B. The endpoints on node A and node C will be hit, but node B will not.

Looking at the failure upstream:
`2022-09-28T11:44:52.1484064Z Sep 28 11:44:49.456: INFO: ExecWithOptions {Command:[/bin/sh -c curl -g -q -s 'http://10.244.2.15:9080/dial?request=hostname&protocol=http&host=fc00:f853:ccd:e793::4&port=32655&tries=1'] Namespace:dualstack-465 PodName:test-container-pod ContainerName:webserver Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false Quiet:false}
2022-09-28T11:44:52.1484676Z Sep 28 11:44:49.456: INFO: >>> kubeConfig: /home/runner/ovn.conf
2022-09-28T11:44:52.1484983Z Sep 28 11:44:49.456: INFO: ExecWithOptions: Clientset creation
2022-09-28T11:44:52.1486061Z Sep 28 11:44:49.456: INFO: ExecWithOptions: execute(POST https://127.0.0.1:32795/api/v1/namespaces/dualstack-465/pods/test-container-pod/exec?command=%2Fbin%2Fsh&command=-c&command=curl+-g+-q+-s+%27http%3A%2F%2F10.244.2.15%3A9080%2Fdial%3Frequest%3Dhostname%26protocol%3Dhttp%26host%3Dfc00%3Af853%3Accd%3Ae793%3A%3A4%26port%3D32655%26tries%3D1%27&container=webserver&container=webserver&stderr=true&stdout=true)
2022-09-28T11:44:52.1486820Z Sep 28 11:44:49.623: INFO: Waiting for responses: map[ovn-control-plane:{}]`

The test container pod is on ovn-worker-2, and it is trying access ::4 nodeport, which also happens to be ovn-control-plane
`ovn-control-plane/kubelet.log:Sep 28 11:37:43 ovn-control-plane kubelet[281]: I0928 11:37:43.272559     281 flags.go:64] FLAG: --node-ip="172.18.0.4,fc00:f853:ccd:e793::4"
`
After 39 tries, it never gets back a result for ovn-control-plane. However, the curls are not failing either, which means they are just hitting other endpoints on each attempt. 

Remember for pod access to another node's node port the packet is not short-circuited inside of OVN and actually leaves the node to go to the destination node. So in this case we need to check the OVN load-balancer configuration on the GR on ovn-control-plane:

`I0928 11:41:46.739169      62 model_client.go:354] Update operations generated as: [{Op:update Table:Load_Balancer Row:map[external_ids:{GoMap:map[k8s.ovn.org/kind:Service k8s.ovn.org/owner:dualstack-465/node-port-service]} name:Service_dualstack-465/node-port-service_TCP_node_router_ovn-control-plane options:{GoMap:map[event:false reject:true skip_snat:false]} protocol:{GoSet:[tcp]} selection_fields:{GoSet:[]} vips:{GoMap:map[10.96.201.91:80:172.18.0.2:8083,172.18.0.3:8083,169.254.169.2:8083 172.18.0.4:32655:172.18.0.2:8083,172.18.0.3:8083,169.254.169.2:8083 [fc00:f853:ccd:e793::4]:32655:[fc00:f853:ccd:e793::2]:8083,[fc00:f853:ccd:e793::3]:8083,[fd69::2]:8083 [fd00:10:96::d9dc]:80:[fc00:f853:ccd:e793::2]:8083,[fc00:f853:ccd:e793::3]:8083,[fd69::2]:8083]}] Rows:[] Columns:[] Mutations:[] Timeout:<nil> Where:[where column _uuid == {7b26af9c-dcfd-4a3c-b8e3-377ab5d8b130}] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUIDName:}]`

We can see for ::4:32655 we have 3 endpoints ::2, ::3, and fd69::2 which is the special masquerade to go to the host. So the load balancer is correct. With each curl the only thing that is changing is the source port. My only theory here is that we are getting unlucky on the dp_hash in OVS that it is never hitting fd69::2. If the packet was getting lost or corrupted we would get a failure in the curl and see another error message in the test output:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dual_stack.go#L444
https://github.com/kubernetes/kubernetes/blob/8ddbd892f24d895bd49563ddaa7614ef3c21f53f/test/e2e/framework/network/utils.go#L314

Either that or we would see long timeouts between each curl attempt.

Locally testing I see up to 9 times before it hits the local endpoint.

**Comment by trozet** [comment] 2022-09-30 21:06
This seems to always fail in the downstream PR. I think we need to recreate it there and try to determine the root cause.

**Comment by npinaeva** [comment] 2022-10-04 12:41
Not sure if we can assume no connection error happened for same-node requests, because https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/network/utils.go#L309 will return `NetexecDialResponse` , which stores connection errors in a separate field https://github.com/kubernetes/kubernetes/blob/ff4e517add1a6077df1317b23fa523b699845ced/test/e2e/framework/network/utils.go#L209-L212
but `resp.Errors` is never checked https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/network/utils.go#L309-L331
And failed request looks something like 
```
{"errors":["Get \"http://[fd2e:6f44:5dd8:c956::17]:30599/hostname\": dial tcp [fd2e:6f44:5dd8:c956::17]:30599: connect: network is unreachable"]}
```

**Comment by trozet** [comment] 2022-10-04 16:00
In downstream this is failing because of a couple compounding issues. The main premise is that hairpin flows will sporadically fail. 
1. The flows for detecting the special IP and DNAT'ing it to the primary IP of the node are broken for ipv6:
```
cookie=0xdeff105, duration=2428.176s, table=0, n_packets=0, n_bytes=0, idle_age=2428, priority=500,ip,in_port=2,nw_src=192.168.111.23,nw_dst=169.254.169.2 actions=ct(commit,table=4,zone=64001,nat(dst=192.168.111.23))

cookie=0xdeff105, duration=2400.107s, table=0, n_packets=37, n_bytes=3478, idle_age=430, priority=500,ipv6,in_port=2,ipv6_src=fd2e:6f44:5dd8:c956::17,ipv6_dst=fd69::2 actions=ct(commit,table=4,zone=64001)
```
2. Because of 1, the curl goes to fd69::2, and that fails:
sh-4.4# curl -g '[fd2e:6f44:5dd8:c956::17]:8083/hostname'
worker-0.ostest.test.metalkube.orgsh-4.4#
sh-4.4#
sh-4.4# curl -g '[fd69::2]:8083/hostname'
curl: (7) Failed to connect to fd69::2 port 8083: No route to host
sh-4.4#

Even though agnhost is listening on all ips:
sh-4.4# netstat -ltpn | grep 8083
tcp6       0      0 :::8083                 :::*                    LISTEN      27387/agnhost

The reason it fails is because duplicate address detection has failed on this interface:
[root@worker-0 ~]# ip a show br-ex
5: br-ex: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 00:ec:fa:1a:64:8d brd ff:ff:ff:ff:ff:ff
    inet 192.168.111.23/24 brd 192.168.111.255 scope global dynamic noprefixroute br-ex
       valid_lft 2787sec preferred_lft 2787sec
    inet 169.254.169.2/29 brd 169.254.169.7 scope global br-ex
       valid_lft forever preferred_lft forever
    inet 192.168.111.4/32 scope global br-ex
       valid_lft forever preferred_lft forever
    inet6 fd69::2/125 scope global dadfailed tentative
       valid_lft forever preferred_lft forever
    inet6 fd2e:6f44:5dd8:c956::17/128 scope global dynamic noprefixroute
       valid_lft 2659sec preferred_lft 2659sec
    inet6 fe80::2ec:faff:fe1a:648d/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

This is because we use this same IP on every node. I think if we just fix the flow that might be enough to solve the entire problem. DAD failing should be OK, because nothing else should ever use this IP other than the hairpin flows from OVN.

**Comment by trozet** [comment] 2022-10-04 20:30
downstream fixed by: https://github.com/ovn-org/ovn-kubernetes/pull/3201

still investigating upstream

**Comment by jcaamano** [comment] 2022-10-07 10:13
I have tried removing parallelization on the dual conversion job.

This job consistently fails the host Network tests on the secondary IP family IPv6:
https://github.com/ovn-org/ovn-kubernetes/actions/runs/3200914218/jobs/5228524177

The analysis is pretty similar to the one above, but is happening with the cluster IP in this occasion. Again, when the hit endpoint is in the same node as the source.

I clearly see a timeout of 5 secs happening where I suspect this communication might be failing, so I would side with @npinaeva that this is just not bad luck:
```
2022-10-06T23:36:51.5286959Z Oct  6 23:36:51.527: INFO: ExecWithOptions: execute(POST https://127.0.0.1:42005/api/v1/namespaces/dualstack-1539/pods/test-container-pod/exec?command=%2Fbin%2Fsh&command=-c&command=curl+-g+-q+-s+%27http%3A%2F%2F10.244.1.33%3A9080%2Fdial%3Frequest%3Dhostname%26protocol%3Dhttp%26host%3Dfd00%3A10%3A96%3A%3A744e%26port%3D80%26tries%3D1%27&container=webserver&container=webserver&stderr=true&stdout=true)
2022-10-06T23:36:56.6049610Z Oct  6 23:36:56.603: INFO: Waiting for responses: map[ovn-worker:{} ovn-worker2:{}]
```

**Closed** 2023-07-20 11:23 UTC
