### ISSUE TITLE
egress IP flake

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#3383] opened 2023-01-26 21:29 UTC
Saw this on a PR that changed no functional code:

https://github.com/ovn-org/ovn-kubernetes/actions/runs/3999244863/jobs/6863266656

[Fail] e2e egress IP validation [It] Should validate egress IP logic when one pod is managed by more than one egressIP object
[11245](https://github.com/ovn-org/ovn-kubernetes/actions/runs/3999244863/jobs/6863266656#step:10:11246)
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/egressip.go:1182
[11246](https://github.com/ovn-org/ovn-kubernetes/actions/runs/3999244863/jobs/6863266656#step:10:11247)
[11247](https://github.com/ovn-org/ovn-kubernetes/actions/runs/3999244863/jobs/6863266656#step:10:11248)
[Fail] e2e egress IP validation [It] Should validate egress IP logic when one pod is managed by more than one egressIP object
[11248](https://github.com/ovn-org/ovn-kubernetes/actions/runs/3999244863/jobs/6863266656#step:10:11249)
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/egressip.go:1043

**Comment by kyrtapz** [comment] 2023-02-01 14:29
`Should validate egress IP logic when one pod is managed by more than one egressIP object` fails with:

```
the test external container did not have any trace of the IPs: [172.18.1.3] being logged, last logs: 172.18.1.4 - - [24/Jan/2023:20:11:06 +0000] "GET / HTTP/1.1" 200 45
```

`172.18.1.4` egress IP was removed in the previous step but it is still being used by the pod, this is caused by a deletion failure where we found SNATs on multiple **(2)** nodes:

```
I0124 20:10:49.368916      40 obj_retry.go:654] Delete event received for *v1.EgressIP egressip-2
I0124 20:10:49.368984      40 egressip.go:1182] Deleting pod egress IP status: {ovn-worker2 172.18.1.4} for EgressIP: egressip-2
I0124 20:10:49.369086      40 model_client.go:374] Mutate operations generated as: [{Op:mutate Table:Logical_Router_Policy Row:map[] Rows:[] Columns:[] Mutations:[{Column:nexthops Mutator:delete Value:{GoSet:[100.64.0.3]}}] Timeout:<nil> Where:[where column _uuid == {6f27614a-8df5-40b8-8e5c-f603332ef143}] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUIDName:}]
I0124 20:10:49.369136      40 model_client.go:383] Delete operations generated as: [{Op:delete Table:NAT Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:<nil> Where:[where column _uuid == {b109244e-87ae-4fd2-a339-ef8ac2d697dd}] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUIDName:}]
I0124 20:10:49.369153      40 model_client.go:383] Delete operations generated as: [{Op:delete Table:NAT Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:<nil> Where:[where column _uuid == {cb6e5d60-2e2e-43d5-a1db-08713fb6e032}] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUIDName:}]
I0124 20:10:49.369201      40 model_client.go:374] Mutate operations generated as: [{Op:mutate Table:Logical_Router Row:map[] Rows:[] Columns:[] Mutations:[{Column:nat Mutator:delete Value:{GoSet:[{GoUUID:b109244e-87ae-4fd2-a339-ef8ac2d697dd} {GoUUID:cb6e5d60-2e2e-43d5-a1db-08713fb6e032}]}}] Timeout:<nil> Where:[where column _uuid == {6a2804eb-058f-4635-87df-d1e1d879a47c}] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUIDName:}]
E0124 20:10:49.369224      40 obj_retry.go:674] Failed to delete *v1.EgressIP egressip-2, error: error removing egress ip egressip-2 nats on router GR_ovn-worker2: unexpectedly found multiple results for provided predicate
```

Following the invalid SNATs we see the following order of events:
```
1. The test switches the nodes
2023-01-24T20:10:47.7308366Z [1mSTEP[0m: 13. Mark egress2Node as assignable and egress1Node as unassignable

2. Label change detected
I0124 20:10:47.756423      40 egressip.go:1829] Egress node: ovn-worker2 about to be initialized
I0124 20:10:47.779340      40 egressip.go:1881] Egress node: ovn-worker about to be removed
E0124 20:10:47.797090      40 egressip.go:970] Allocator error: EgressIP: egressip-2 assigned to node: ovn-worker which does not have egress label, will attempt rebalancing
E0124 20:10:47.797090      40 egressip.go:970] Allocator error: EgressIP: egressip-2 assigned to node: ovn-worker which does not have egress label, will attempt rebalancing
E0124 20:10:47.797090      40 egressip.go:970] Allocator error: EgressIP: egressip-2 assigned to node: ovn-worker which does not have egress label, will attempt rebalancing

3. egressip-2 gets removed and pod starts using the standby  (egressip):
I0124 20:10:47.797155      40 egressip.go:1182] Deleting pod egress IP status: {ovn-worker 172.18.1.4} for EgressIP: egressip-2
I0124 20:10:47.813040      40 egressip.go:1209] Pod egressip-9723_e2e-egressip-pod-1 has standby egress IP [egressip]
I0124 20:10:47.813154      40 egressip.go:1138] Adding pod egress IP status: {ovn-worker 172.18.1.3} for EgressIP: egressip and pod: e2e-egressip-pod-1/egressip-9723

4. egressip-2 gets assigned to ovn-worker2, gets added as a standby
I0124 20:10:47.827083      40 egressip.go:1650] Current assignments are: map[]
I0124 20:10:47.827178      40 egressip.go:1652] Will attempt assignment for egress IP: 172.18.1.4
I0124 20:10:47.827249      40 egressip.go:1692] Attempting assignment on egress node: &{egressIPConfig:0xc000443560 mgmtIPs:[[10 244 1 2]] allocations:map[] healthClient:0xc000461260 isReady:true isReachable:true isEgressAssignable:true name:ovn-worker2}
I0124 20:10:47.827331      40 egressip.go:1721] Successful assignment of egress IP: 172.18.1.4 on node: &{egressIPConfig:0xc000443560 mgmtIPs:[[10 244 1 2]] allocations:map[] healthClient:0xc000461260 isReady:true isReachable:true isEgressAssignable:true name:ovn-worker2}
W0124 20:10:47.827442      40 egressip.go:1122] EgressIP object egressip-2 will not be configured for pod egressip-9723_e2e-egressip-pod-1 since another egressIP object egressip is serving it
W0124 20:10:47.827442      40 egressip.go:1122] EgressIP object egressip-2 will not be configured for pod egressip-9723_e2e-egressip-pod-1 since another egressIP object egressip is serving it
I0124 20:10:47.827531      40 egressip.go:1605] Patching status on EgressIP egressip-2: [{ovn-worker2 172.18.1.4}]
I0124 20:10:47.827989      40 event.go:285] Event(v1.ObjectReference{Kind:"EgressIP", Namespace:"", Name:"egressip-2", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'UndefinedRequest' EgressIP object egressip-2 will not be configured for pod egressip-9723_e2e-egressip-pod-1 since another egressIP object egressip is serving it, this is undefined

5. egressip gets removed and pod starts using the standby (egressip-2):
E0124 20:10:47.844004      40 egressip.go:970] Allocator error: EgressIP: egressip assigned to node: ovn-worker which does not have egress label, will attempt rebalancing
E0124 20:10:47.844004      40 egressip.go:970] Allocator error: EgressIP: egressip assigned to node: ovn-worker which does not have egress label, will attempt rebalancing
E0124 20:10:47.844004      40 egressip.go:970] Allocator error: EgressIP: egressip assigned to node: ovn-worker which does not have egress label, will attempt rebalancing
I0124 20:10:47.844174      40 egressip.go:1182] Deleting pod egress IP status: {ovn-worker 172.18.1.3} for EgressIP: egressip
I0124 20:10:47.850701      40 egressip.go:1209] Pod egressip-9723_e2e-egressip-pod-1 has standby egress IP [egressip-2]
[BUG!! Even though egressip-2 already moved to ovn-worker2 we add the egress IP SNAT on ovn-worker]
I0124 20:10:47.850809      40 egressip.go:1138] Adding pod egress IP status: {ovn-worker 172.18.1.4} for EgressIP: egressip-2 and pod: e2e-egressip-pod-1/egressip-9723

6. egressip gets assigned to ovn-worker2, gets added as a standby:
I0124 20:10:47.876634      40 egressip.go:1650] Current assignments are: map[172.18.1.4:{Node:ovn-worker2 Name:egressip-2}]
I0124 20:10:47.876647      40 egressip.go:1652] Will attempt assignment for egress IP: 172.18.1.3
I0124 20:10:47.876656      40 egressip.go:1692] Attempting assignment on egress node: &{egressIPConfig:0xc000443560 mgmtIPs:[[10 244 1 2]] allocations:map[172.18.1.4:egressip-2] healthClient:0xc000461260 isReady:true isReachable:true isEgressAssignable:true name:ovn-worker2}
I0124 20:10:47.876675      40 egressip.go:1721] Successful assignment of egress IP: 172.18.1.3 on node: &{egressIPConfig:0xc000443560 mgmtIPs:[[10 244 1 2]] allocations:map[172.18.1.4:egressip-2] healthClient:0xc000461260 isReady:true isReachable:true isEgressAssignable:true name:ovn-worker2}
W0124 20:10:47.876721      40 egressip.go:1122] EgressIP object egressip will not be configured for pod egressip-9723_e2e-egressip-pod-1 since another egressIP object egressip-2 is serving it
W0124 20:10:47.876721      40 egressip.go:1122] EgressIP object egressip will not be configured for pod egressip-9723_e2e-egressip-pod-1 since another egressIP object egressip-2 is serving it
I0124 20:10:47.876741      40 egressip.go:1605] Patching status on EgressIP egressip: [{ovn-worker2 172.18.1.3}]
I0124 20:10:47.877147      40 event.go:285] Event(v1.ObjectReference{Kind:"EgressIP", Namespace:"", Name:"egressip", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'UndefinedRequest' EgressIP object egressip will not be configured for pod egressip-9723_e2e-egressip-pod-1 since another egressIP object egressip-2 is serving it, this is undefined

7. Status update of egressip-2(from Step 4) gets handled:
I0124 20:10:47.881837      40 obj_retry.go:558] Update event received for *v1.EgressIP egressip-2
[BUG pod is missing an snat on ovn-worker2 so we add it here, ending up with two SNATs]
I0124 20:10:47.900718      40 egressip.go:1138] Adding pod egress IP status: {ovn-worker2 172.18.1.4} for EgressIP: egressip-2 and pod: e2e-egressip-pod-1/egressip-9723
```

Looks like a race where the standby assignment in step 5 used egressip-2 status that did not reflect that it already moved to ovn-worker2, then in step 7 an additional SNAT was added to ovn-worker2.

**Comment by kyrtapz** [comment] 2023-02-02 10:40
I don't think this issue is likely to happen in real world, the standby egressip has to be reassigned at the same time as it is being configured for a pod.

Additionally with the change made [here](https://github.com/ovn-org/ovn-kubernetes/pull/3371/files#diff-5d62dde13a2856ea3d4b324968dbaeed261fcb74cb3b81909edf40a6634fa1f4R1107) the following error should no longer happen:
```
Failed to delete *v1.EgressIP egressip-2, error: error removing egress ip egressip-2 nats on router GR_ovn-worker2: unexpectedly found multiple results for provided predicate
```

I think we should stop [relying on egress IP status](https://github.com/ovn-org/ovn-kubernetes/blob/caba9beceee0f6354ac94be6633cda221c50ed9b/go-controller/pkg/ovn/egressip.go#L2129) during standby assignment but I am not sure how to that reliably.

**Comment by tssurya** [comment] 2024-03-12 20:52
Too rare a flake, have not run into this after that one time. Closing this. Let's reopen if we run into this.

**Closed by tssurya** 2024-03-12 20:52 UTC
Labels: ci-flake
