### ISSUE TITLE
Implement Kubernetes `ExternalTrafficPolicy`

### ISSUE THREAD

**Issue by astoycos** [ovn-org/ovn-kubernetes#1950] opened 2021-01-13 16:59 UTC
As exposed by https://bugzilla.redhat.com/show_bug.cgi?id=1903408, it is clear that currently OVN-K8s does not implement the Kubernetes Nodeport Service `externalTrafficPolicy` flag.  A short description for the feature can be shown below 

```yaml
externalTrafficPolicy denotes if this Service desires to route external traffic to node-local
or cluster-wide endpoints. "Local" preserves the client source IP and avoids a second hop
for LoadBalancer and NodePort type services, but risks potentially imbalanced traffic
spreading. "Cluster" obscures the client source IP and may cause a second hop to
another node, but should have good overall load-spreading.
```
Once the move back to shared gateway is solidified we can continue the architecture discussion for the feature, this issue will serve as a placeholder for the work 

**Design:** 

With the shared GW topology we should be able to implement this feature by steering ingress traffic to either the node local or cluster wide endpoints using shared GW flows....
TBD

**Comment by girishmg** [comment] 2021-01-16 19:17
closing this as duplicate of #1951

**Closed by girishmg** 2021-01-16 19:17 UTC
